### ISSUE TITLE
subtitle match

### ISSUE THREAD

**Issue by cauchy2k** [fedemotta/subseek#4]
thanks for your great work, i have a problem the subtitle is downloaded but  if the name of the subtitle inside the rar or zip file example: life in pieces 3x13 doesnt match with my file life in pieces s03e13 then the script discard it.
thank you very much this is a very clever script.

**Comment by fedemotta** [comment]
Hi @cauchy2k 
So strange!

Could you send me the subtitle link to download it and make a test?

Cheers

**Comment by cauchy2k** [comment]
thanks for your help. this is the link to the subtitle
http://www.subdivx.com/bajar.php?id=528309&u=8
my file is Life.in.Pieces.S03E13.Therapy.Cheating.Shoes.Movie.xvid.360p@1404
and subtitle inside rar file is Life in Pieces 3x13 - Therapy Cheating
Shoes Movie.AVS_SVA.es-es.srt
also i get this kind of message
*Starting process for
"L:\18-09-17\archivos\Everything.Sucks!.S01E07.Cheesecake.to.a.Fat.Man.810
"*
*Valid series name*
*Searching 'everything sucks s01e07' in 'subdivx.com <http://subdivx.com>'*
*1 matches found in 'subdivx.com <http://subdivx.com>'*
*Searching in
http://www.subdivx.com/X6XNTI3MTA2X-everything-sucks-s01e07.html
<http://www.subdivx.com/X6XNTI3MTA2X-everything-sucks-s01e07.html>*
*No subtitles with '2015/09/28 subdivx.com <http://subdivx.com> subtitle
page'*
*No subtitles with '2015/09/28 subdivx.com <http://subdivx.com> search
page'*
*No subtitles with '2015/04/01 subdivx.com <http://subdivx.com> subtitle
page'*
*1 subtitles with '2015/03/01 subdivx.com <http://subdivx.com> subtitle
page'*
*No subtitles with '2014/12/01 subdivx.com <http://subdivx.com> subtitle
page'*
*No subtitles with '2014/12/01 subdivx.com <http://subdivx.com> search
page'*
*Subtitle File URL: http://www.subdivx.com/bajar.php?id=527106&u=8
<http://www.subdivx.com/bajar.php?id=527106&u=8>*
*   Text To Search: everything sucks s01e07*
*    Text To Match: subtitulo de everything sucks s01e07 e07 como un
cheesecake para un gordo subt├¡tulo original de netflix en espa├▒ol latino
para versiones webrip strife y dem├ís*
*   Text Match (%): 100.0%*
*File downloaded*
*Subtitle file not found*
*Searching 'everything sucks s01e07' in 'google.com <http://google.com>'*
*No match found in 'google.com <http://google.com>'*
*Searching 'everything sucks s01e07' in 'duckduckgo.com
<http://duckduckgo.com>'*
*No match found in 'duckduckgo.com <http://duckduckgo.com>'*
*Best subtitle not found*
*Ending process for
"L:\18-09-17\archivos\Everything.Sucks!.S01E07.Cheesecake.to.a.Fat.Man.810
"*

dont understand why it says subtitle file not found
thank you very much for your help this script is awesome.



2018-04-26 8:59 GMT-04:00 Federico Nicolás Motta <notifications@github.com>:

**Comment by fedemotta** [comment]
@cauchy2k 
I will make a test. 

The movie file is Life.in.Pieces.S03E13.Therapy.Cheating.Shoes.Movie.xvid.360p@1404.mkv

right?

What command are you running?

**Comment by fedemotta** [comment]
@cauchy2k Also is there any other video file in that folder?

**Comment by cauchy2k** [comment]
yes that's the file name of that tv show i have in that folder. it's a folder
with 2250 tv shows files. life in pieces is a tv show
this is the command i am running
python -m subseek -p L:\18-09-17\archivos -v
thanks for your help

2018-04-26 10:35 GMT-04:00 Federico Nicolás Motta <notifications@github.com>
:

**Comment by fedemotta** [comment]
Hello, sorry for the delay in my response. I tried with the same filename and command and the subtitle downloaded started with:

>1
00:00:00,167 --> 00:00:04,376
www.subtitulamos.tv
2
00:00:04,751 --> 00:00:07,001
HISTORIA UNO:
JOAN LO VENTILA
3
00:00:10,375 --> 00:00:12,042
Hola, abuela.
 

fedemotta@federico:~/Downloads/Life in Pieces$ python -m  subseek -p /home/fedemotta/Downloads/Life\ in\ Pieces/  -v

-------------------------------------------------------------------------------
                      
Starting process for "/home/fedemotta/Downloads/Life in Pieces/Life.in.Pieces.S03E13.Therapy.Cheating.Shoes.Movie.xvid.360p@1404"
Valid series name
Searching 'life in pieces s03e13' in 'subdivx.com'
1 matches found in 'subdivx.com'
Searching in http://www.subdivx.com/X6XNTI4MzA5X-life-in-pieces-s03e13.html
No subtitles with '2015/09/28 subdivx.com subtitle page'
No subtitles with '2015/09/28 subdivx.com search page'
No subtitles with '2015/04/01 subdivx.com subtitle page'
1 subtitles with '2015/03/01 subdivx.com subtitle page'
No subtitles with '2014/12/01 subdivx.com subtitle page'
No subtitles with '2014/12/01 subdivx.com search page'
Subtitle File URL: http://www.subdivx.com/bajar.php?id=528309&u=8
   Text To Search: life in pieces s03e13 xvid
    Text To Match: subtitulo de life in pieces s03e13 traducidos en www subtitulamos tv en español españa para avs sva ¡mas versiones en nuestra web
   Text Match (%): 73.0%
File downloaded
Subtitle file found in rar
Ending process for "/home/fedemotta/Downloads/Life in Pieces/Life.in.Pieces.S03E13.Therapy.Cheating.Shoes.Movie.xvid.360p@1404"

-------------------------------------------------------------------------------

It seems to be working fine. If this is not the sub, it was badly upload to subdivx.

**Comment by cauchy2k** [comment]
thank you very much for your support, I 'll try again or maybe from Linux.

**Comment by cauchy2k** [comment]
Thanks again I did a test from Ubuntu and it worked, the problem seems to be in Windows.
